GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJ3YXdhbiIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiaWF0IjoxNzc2ODM3NjE2LCJleHAiOjE3NzY4Mzg1MTZ9.u0LqiADvgEDxny2SCi5Nn_uiagORIVCrD7SrwVZSOhA

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "wawan",
    "email": "email@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}


###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password": "123456"
}


###
GET http://localhost:3000/token
###
DELETE http://localhost:3000/logout